---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution|lower }}.yml"
    - "../vars/empty.yml"
  tags: [always]

- name: Gather instance facts
  setup:

- name: Stop playbook if the installation is unmanaged and the host is not the local host
  meta: end_host
  when:
    - not wireguard_installation_managed|bool
    - ansible_hostname != host

- name: Perform managed installation of WireGuard
  include_tasks: "install.yml"
  when: wireguard_installation_managed|bool

- name: Create WireGuard configuration directory
  file:
    dest: "{{ wireguard_remote_directory }}"
    state: directory
    mode: 0700
  tags:
    - wg-config

- name: Generate WireGuard configuration file
  template:
    src: wg.conf.j2
    dest: "{{ wireguard_remote_directory }}/{{ wireguard_conf_name }}.conf"
    owner: root
    group: root
    mode: 0600
  tags:
    - wg-config
  notify:
    - restart wireguard

- name: Perform managed post-installation of WireGuard
  include_tasks: "post_install.yml"
  when: wireguard_installation_managed|bool
